### ISSUE TITLE
Add `codecov` for coverage?

### ISSUE THREAD

**Issue by ForsakenHarmony** [mulesoft-labs/datatype-expansion#7]
Should we add [codecov](https://codecov.io/gh/mulesoft-labs/datatype-expansion/commits) for coverage info? related to #5

**Comment by jstoiko** [comment]
sure. `codecov` or `coveralls` like we have in [Osprey](https://github.com/mulesoft/osprey) (see badge in README). whatever you prefer.

**Comment by ForsakenHarmony** [comment]
I don't really care which one myself, haven't used either, just thought it would be a nice to have
